version: '3'
services:
  api:
    container_name: muscles-api
    hostname: server
    build: .
    command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/opt
    ports:
      - '8000:8000'
    tty: true