version: '3'
services:
  db: 
    container_name: muscles-db
    hostname: postgresserver
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    
  api:
    container_name: muscles-api
    hostname: server
    build: .
    env_file:
      - .env
    command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/opt
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - db
  
  adminer:
    container_name: muscles-adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: null